"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['GARCHETTE']

# %% ../nbs/00_core.ipynb 3
import numpy as np
from arch import arch_model
from functools import cached_property

# %% ../nbs/00_core.ipynb 4
class GARCHETTE:
    
    def __init__(self) -> None:
        self.params = None
        self._is_fit = False
        self._sig2_init = None

    def fit(self,y):
        self._y = y
        res = arch_model(y,mean='zero',dist='t').fit(disp='off')
        self.params = res.params
        self._sig2_init = res.conditional_volatility[0]**2
        self._is_fit = True
        return self
    
    @cached_property
    def vs(self):
        ...

    @cached_property
    def std_resid(self):
        return self._y / np.sqrt(self.vs)

    def simulate(self,horizon:int, n_rep=1000):
        ...
