"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'g']

# %% ../nbs/00_core.ipynb 3
def foo(): 
    ...
    pass

# %% ../nbs/00_core.ipynb 4
def g():
    pass
